### ISSUE TITLE
New order for the other locales tab: CA

### ISSUE THREAD

**Issue by javiercasares** [GlotPress/gp-translation-helpers#191]
`'ca' => array( 'ca_valencia', 'bal' 'es', 'oci', 'arg', 'gl', 'fr_FR', 'it_IT', 'pt_PT', 'ro_RO', 'la' )`

**Comment by javiercasares** [comment]
@amieiro

**Comment by amieiro** [comment]
Hi @javiercasares 

I have made some updates in the slugs:
- [Catalan (Valencian)](https://github.com/WordPress/wordpress.org/blob/6d8dde5b1823d5cfcc7134c8eae4531de6926be9/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L482).
- [Aragonese](https://github.com/WordPress/wordpress.org/blob/6d8dde5b1823d5cfcc7134c8eae4531de6926be9/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L185).
- [French](https://github.com/WordPress/wordpress.org/blob/6d8dde5b1823d5cfcc7134c8eae4531de6926be9/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L1108). 
- [Italian](https://github.com/WordPress/wordpress.org/blob/6d8dde5b1823d5cfcc7134c8eae4531de6926be9/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L1460).
- [Portuguese (Portugal)](https://github.com/WordPress/wordpress.org/blob/6d8dde5b1823d5cfcc7134c8eae4531de6926be9/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L2116).
- [Romanian](https://github.com/WordPress/wordpress.org/blob/6d8dde5b1823d5cfcc7134c8eae4531de6926be9/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L2184).

```
'ca' => array( 'ca-val', 'bal', 'es', 'oci', 'an', 'gl', 'fr', 'it', 'pt', 'ro', 'la' ),
```

This is a preview with this improvement. Some languages don't appear because they have translations for this example (e.g., Catalan (Valencian) and Latin). 

![image](https://github.com/GlotPress/gp-translation-helpers/assets/1667814/a7452b2c-aed6-4f4f-a756-148417a799ef)
