### ISSUE TITLE
Source locale is not clear for discussions

### ISSUE THREAD

**Issue by MatzeKitt** [GlotPress/gp-translation-helpers#22]
I created a project in GlotPress with locales de and de-ch. Then I added two different translations for the same string in these two locales. Then, I started a discussion in de.

In de, the discussion shows this information on top: 3 Comments (de) Show all (3) | de only (0)

In de-ch, the discussion shows this information on top: 3 Comments (de-ch) Show all (3) | de-ch only (0)

And all comments are shown in both locales. And for both locales it shows that the comments are made in either this exact locale (if you check the first information item on top) or none (if you check the last information item on top).

So there’s something broken here, I think:

- The information, to which locale the discussion belongs to, is wrong.
- Maybe as a result of this, the `de only (0)` and `de-ch only (0)` both show no comments.

**Comment by naokomc** [comment]
I'm seeing this too.
<img width="669" alt="image" src="https://user-images.githubusercontent.com/34067/155464672-b78dbe10-16cb-4c56-a198-fdc5cf179202.png">

Comments had meta information (locale and translation) attached only when there is a _Current_ translation.
If a string only had a translation set to a status other than _Current_, the "Translation: xxx..." section didn't show up.

**Comment by trymebytes** [comment]
@MatzeKitt Thanks for the feedback. Please note that comments posted with either of these topics (see screenshot below) selected will have no locale attached. Can you remember which topic you selected while submitting the comment? Also, when the `Show all` filter is selected, it shows ALL comments posted for that string  regardless of the locale of the discussion page where it was posted and including comments posted without locales attached.
<img width="865" alt="Screenshot 2022-02-25 at 13 51 20" src="https://user-images.githubusercontent.com/2834132/155739476-577d048b-978c-4b9c-94ad-62a55a4a5298.png">

@naokomc Thanks for the feedback, when there's no current translation, the "Translation: xxx..." section will not show, which lets everyone see that there was no current translation as at the time the comment was made. I also don't think we want to show the rejected translation there as it may be confusing but please do not hesitate to share more ideas regarding this.

However, we found a bug which was responsible for not allowing the locale show up and that has been fixed in this [PR](https://github.com/GlotPress/gp-translation-helpers/pull/27)

**Comment by naokomc** [comment]
About the rejected translation, I thought translators may want to dispute the rejection decision by providing additional information for the reviewer. But that may be an edge case, and they can always create different suggestions and comments. I'm ok with disabling this on non-current translations.

On the other hand, when there is a Waiting status translation, I think it really makes sense to add the meta info (the locale and Waiting translation) for the “Question about translating to Japanese” topic comment. The translator and reviewer will need to know which translation they are discussing.

https://user-images.githubusercontent.com/34067/156122502-93cd6173-748b-457c-a5bf-fb08834c1b92.mov

**Comment by trymebytes** [comment]
Thanks @naokomc, I just tried reproducing this on the latest version of the plugin(there have been new merges lately) and I found out that the locale shows up but the 'Waiting translation' does not. We'll look into this, thanks!

**Comment by amieiro** [comment]
I have a similar setup in my local environment, with 2 locales (es and gl) and 1 project (WooCommerce).

I have made 2 discussions with 1 reply in Spanish and the filter is working fine.

![image](https://user-images.githubusercontent.com/1667814/193575758-2e5fcada-abba-44b5-846e-01686d55f8b7.png)

If I change to the other locale (Galician), the filter looks fine.

![image](https://user-images.githubusercontent.com/1667814/193575987-f93ece4e-6ed8-433a-9330-9816528279cf.png)

And if I click on "gl only (0)", the discussion is empty.

So I think the filter is working fine. 

![image](https://user-images.githubusercontent.com/1667814/193576301-c353ab01-fe20-4239-b5fe-bb1e1fad48bf.png)

@MatzeKitt Can you review it so we can close the issue? Thank you.

**Comment by trymebytes** [comment]
I think we can close this now.
